### Spis treści:
1. [Biblioteka NumPy - podstawowe informacje](#0)
2. [Skalar](#1)
3. [Wektor](#2)
4. [Macierz](#3)
5. [Tensor](#4)

### <a name='0'></a> 1. Biblioteka NumPy - podstawowe informacje

Biblioteka NumPy to podstawowe narzędzie stosu uczenia maszynowego z użyciem języka programowania Python.

Pozwala ona przeprowadzić efektywne operacje na strukturach danych, które są najczęściej wykorzystywane w uczeniu maszynowym: wektor, macierz, tensor.

Jako, że biblioteka NumPy jest jedną z najczęściej używanych bibliotek podczas pracy z danymi, w tym rozdziale przedstawione zostaną operacje NumPy najczęściej przeprowadzane podczas pracy wymagającej zastosowania uczenia maszynowego.

NumPy (*Numerical Python*) to popularna biblioteka w języku Python, która jest używana głównie do obliczeń numerycznych i manipulacji danymi w postaci tablic. Poniżej kilka kluczowych cech i zastosowań biblioteki NumPy:

1. Tablice NumPy: NumPy wprowadza typ danych tablicy n-wymiarowej (ndarray), który umożliwia efektywną i szybką pracę z wielowymiarowymi danymi numerycznymi. Te tablice są podobne do list, ale oferują znacznie większą wydajność i funkcjonalność.

2. Szybkość: NumPy jest napisane w języku C, co pozwala na wydajne obliczenia numeryczne. Dzięki temu jest idealne do przetwarzania dużych zbiorów danych i wykonywania zaawansowanych operacji matematycznych.

3. Funkcje matematyczne: NumPy zawiera wiele funkcji matematycznych, takich jak operacje arytmetyczne, funkcje trygonometryczne, operacje na macierzach i wiele innych, co czyni go potężnym narzędziem do analizy danych i obliczeń naukowych.

4. Indeksowanie i wycinanie: NumPy oferuje zaawansowane techniki indeksowania i wycinania tablic, co ułatwia dostęp do konkretnych danych w tablicach wielowymiarowych.

5. Operacje na tablicach: NumPy umożliwia wykonywanie operacji na całych tablicach bez potrzeby pętli. To pozwala na efektywne obliczenia na danych.

6. Integracja z innymi bibliotekami: NumPy jest często używane w połączeniu z innymi bibliotekami do analizy danych, takimi jak Pandas, Matplotlib do wizualizacji, czy SciPy do bardziej zaawansowanych obliczeń naukowych.

7. Wsparcie dla rozszerzeń: NumPy ma wiele rozszerzeń, takich jak NumPy-BLAS, które zapewniają jeszcze lepszą wydajność w obliczeniach numerycznych.



Dzięki tym cechom NumPy jest szeroko stosowane w dziedzinach takich jak analiza danych, uczenie maszynowe, inżynieria, nauki przyrodnicze i wiele innych, gdzie wymagane są obliczenia numeryczne na dużą skalę.

### <a name='1'></a> 2. Skalar

**Skalar**- wartość numeryczna, która może przyjąć postać liczby całkowitej (int) lub liczby rzeczywistej (float).

###Import bibliotek

In [ ]:
import numpy as np

In [ ]:
scalar = 5
print(scalar)
print(type(scalar))

5
<class 'int'>


In [ ]:
scalar = 5.0
print(scalar)
print(type(scalar))

5.0
<class 'float'>


### <a name='2'></a> 3. Wektor

In [ ]:
vector = np.array([2, 4, -6, 5])
print(vector)
print(type(vector))
print(f'Rozmiar wektora {vector.shape}')
print(f'Typ danych wektora: {vector.dtype}')
print(f'Rząd {vector.ndim}')                  #Tensor rzędu 1 inaczej wektor.
print(f'Długość: {len(vector)}')

[ 2  4 -6  5]
<class 'numpy.ndarray'>
Rozmiar wektora (4,)
Typ danych wektora: int64
Rząd 1
Długość: 4


In [ ]:
vector = np.array([2, 4, -6, 5], dtype='float')
print(vector)
print(f'Typ danych wektora: {vector.dtype}')

[ 2.  4. -6.  5.]
Typ danych wektora: float64


### <a name='3'></a> 4. Macierz

In [ ]:
array = np.array([[2, 6, 3],
                  [5, -3, 4]])

print(array)
print(type(array))
print(f'Rozmiar macierzy: {array.shape}')
print(f'Typ danych macierzy: {array.dtype}')
print(f'Rząd: {array.ndim}')
print(f'Długość: {len(array)}')

[[ 2  6  3]
 [ 5 -3  4]]
<class 'numpy.ndarray'>
Rozmiar macierzy: (2, 3)
Typ danych macierzy: int64
Rząd: 2
Długość: 2


In [ ]:
array = np.array([[2, 6, 3],
                  [5, -3, 4],
                  [4, 2, 1]], dtype = 'float')

print(array)
print(type(array))
print(f'Rozmiar macierzy: {array.shape}')
print(f'Typ danych macierzy: {array.dtype}')
print(f'Rząd: {array.ndim}')                  #Ilość nawiasów kwadratowych
print(f'Długość: {len(array)}')               #Ilość rzędów w macierzy

[[ 2.  6.  3.]
 [ 5. -3.  4.]
 [ 4.  2.  1.]]
<class 'numpy.ndarray'>
Rozmiar macierzy: (3, 3)
Typ danych macierzy: float64
Rząd: 2
Długość: 3


### <a name='4'></a> 5. Tensor

Tensor jest uogólnieniem wektora czy też macierzy na wyższe wymiary.

Jeżeli będziemy rozpatrywać wyższe wymiary to będziemy mówić o tensorze.

Tensory wykorzystywane są przede wszytskim do zapisywania danych takich jak obrazy czy wideo.

In [ ]:
tensor = np.array([
    [[1, 2, 3],
     [4, 5, 6]],
    [[7, 8, 9],
     [3, 7, 3]]
])

print(tensor)
print(type(tensor))
print(f'Rozmiar macierzy: {tensor.shape}')   #2x2X3 - aby lepiej to wyjaśnić mamy 2 macierze poprzedniego wymiaru, który rozważaliśmy o wymiarach 2 na 3
print(f'Typ danych macierzy: {tensor.dtype}')
print(f'Rząd: {tensor.ndim}')                  #Ilość nawiasów kwadratowych
print(f'Długość: {len(tensor)}')               #Tensor składa się jakby z dwóch macierzy

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [3 7 3]]]
<class 'numpy.ndarray'>
Rozmiar macierzy: (2, 2, 3)
Typ danych macierzy: int64
Rząd: 3
Długość: 2


In [ ]:
tensor = np.array([
    [[1, 2, 3],
     [4, 5, 6]],
    [[7, 8, 9],
     [3, 7, 3]],
    [[2, 3, 4],
     [5, 6, 7]]
])

print(tensor)
print(type(tensor))
print(f'Rozmiar macierzy: {tensor.shape}')   #2x2X3 - aby lepiej to wyjaśnić mamy 2 macierze poprzedniego wymiaru, który rozważaliśmy o wymiarach 2 na 3
print(f'Typ danych macierzy: {tensor.dtype}')
print(f'Rząd: {tensor.ndim}')                  #Ilość nawiasów kwadratowych
print(f'Długość: {len(tensor)}')

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [3 7 3]]

 [[2 3 4]
  [5 6 7]]]
<class 'numpy.ndarray'>
Rozmiar macierzy: (3, 2, 3)
Typ danych macierzy: int64
Rząd: 3
Długość: 3
