###Biblioteka NumPy

### Spis treści:
1. [Biblioteka NumPy - podstawowe informacje](#0)
2. [Wektor](#1)
3. [Macierz](#2)


### <a name='0'></a> 1. Biblioteka NumPy - podstawowe informacje

Biblioteka NumPy to podstawowe narzędzie stosu uczenia maszynowego z użyciem języka programowania Python.

Pozwala ona przeprowadzić efektywne operacje na strukturach danych, które są najczęściej wykorzystywane w uczeniu maszynowym: wektor, macierz, tensor.

Jako, że biblioteka NumPy jest jedną z najczęściej używanych bibliotek podczas pracy z danymi, w tym rozdziale przedstawione zostaną operacje NumPy najczęściej przeprowadzane podczas pracy wymagającej zastosowania uczenia maszynowego.


NumPy (*Numerical Python*) to popularna biblioteka w języku Python, która jest używana głównie do obliczeń numerycznych i manipulacji danymi w postaci tablic. Poniżej kilka kluczowych cech i zastosowań biblioteki NumPy:

1. Tablice NumPy: NumPy wprowadza typ danych tablicy n-wymiarowej (ndarray), który umożliwia efektywną i szybką pracę z wielowymiarowymi danymi numerycznymi. Te tablice są podobne do list, ale oferują znacznie większą wydajność i funkcjonalność.

2. Szybkość: NumPy jest napisane w języku C, co pozwala na wydajne obliczenia numeryczne. Dzięki temu jest idealne do przetwarzania dużych zbiorów danych i wykonywania zaawansowanych operacji matematycznych.

3. Funkcje matematyczne: NumPy zawiera wiele funkcji matematycznych, takich jak operacje arytmetyczne, funkcje trygonometryczne, operacje na macierzach i wiele innych, co czyni go potężnym narzędziem do analizy danych i obliczeń naukowych.

4. Indeksowanie i wycinanie: NumPy oferuje zaawansowane techniki indeksowania i wycinania tablic, co ułatwia dostęp do konkretnych danych w tablicach wielowymiarowych.

5. Operacje na tablicach: NumPy umożliwia wykonywanie operacji na całych tablicach bez potrzeby pętli. To pozwala na efektywne obliczenia na danych.

6. Integracja z innymi bibliotekami: NumPy jest często używane w połączeniu z innymi bibliotekami do analizy danych, takimi jak Pandas, Matplotlib do wizualizacji, czy SciPy do bardziej zaawansowanych obliczeń naukowych.

7. Wsparcie dla rozszerzeń: NumPy ma wiele rozszerzeń, takich jak NumPy-BLAS, które zapewniają jeszcze lepszą wydajność w obliczeniach numerycznych.



Dzięki tym cechom NumPy jest szeroko stosowane w dziedzinach takich jak analiza danych, uczenie maszynowe, inżynieria, nauki przyrodnicze i wiele innych, gdzie wymagane są obliczenia numeryczne na dużą skalę.

### <a name='1'></a> 2. Wektor

###Zadanie 1. Utwórz wektor

Odpowiedź: Należy użyć biblioteki NumPy do utworzenia tablicy jednowymiarowej.

In [ ]:
#Wczytywanie biblioteki
import numpy as np
#Utworzenie wektora przedstawiającego wiersz
vector_row = np.array([1, 2, 3])
#Utworzenie wektora przedstawiającego kolumnę
vector_column = np.array([[1],
                          [2],
                          [3]])

In [ ]:
vector_row

array([1, 2, 3])

In [ ]:
vector_column

array([[1],
       [2],
       [3]])

Podstawową strukturą danych biblioteki numPy jest tablica wektorowa.

Wektor to po prostu tablica jednowymiarowa.

Aby utworzyć wektor należy zdefiniować tablicę jednowymiarową.

Podobnie jak w przypadku wektora, także tablica może być przedstawiona poziomo (na przykład wiersz) lub pionowo (na przykład kolumna).

### <a name='2'></a> 3. Macierz

###Zadanie 1. Utwórz macierz

Odpowiedź: Należy użyć biblioteki NumPy do utworzenia tablicy dwuwymiarowej.

In [ ]:
#Wczytywanie biblioteki
import numpy as np
#Utworzenie tablicy dwuwymiarowej
matrix = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])

In [ ]:
matrix

array([[1, 2],
       [3, 4],
       [5, 6]])

Do utworzenia macierzy można wykorzystać oferowaną przez bibliotekę NumPy tablicę dwuwymiarową.

W przedstawionym ponizej rozwiązaniu macierz składa się z trzech wierszy oraz trzech kolumn.

Nalezy jednak wskazać, iż NumPy ma dedykowaną macierzy strukturę danych, która zostanie zaprezentowana w kolejnymm fragmencie kodu.

Muszę jednak podkreslić, że z dwóch powodów nie zaleca się stosowania tej struktury.

Po pierwsze, tablica jest faktycznie standardową strukturą dancyh w bibliotece NumPy.

Po drugie, większość operacji przeprowadzanych za pomocą NumPy zwraca tablicę, a nie obiekt macierzy.

###Zadanie 2. Utwórz macierz rzadką

Chcemy w efektywny sposób przedstawić dane zawierajace niewiele wartości niezerowych.

Odpowiedź: Należy użyć bibliotek do utworzenia macierzy rzadkiej (ang. sparse matrix).


In [ ]:
#Wczytywanie bibliotek
import numpy as np
from scipy import sparse
#Utworzenie macierzy
matrix = np.array([[0, 0],
                   [0, 1],
                   [3, 0]])

#Utworzenie macierzy w formacie CSR
matrix_sparse = sparse.csr_matrix(matrix)

In [ ]:
matrix

array([[0, 0],
       [0, 1],
       [3, 0]])

In [ ]:
matrix_sparse

<3x2 sparse matrix of type '<class 'numpy.int64'>'
	with 2 stored elements in Compressed Sparse Row format>

In [ ]:
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


Podczas stosowania uczenia maszynowego bardzo często zdarza się, że masz do dyspozycji ogromną ilość danych, przy czym większość elementów w zbiorze danych to zera.

Na przykład wyobraź sobie macierz, w której kolumny przedstawiają filmy oferowane przez serwis Netflix, natomiast wiersze to użytkownicy serwisu.

Wartości w tej macierzy określają, ile razy użytkownik obejrzał dany film. Ta macierz będzie się składała z dziesiątek tysięcy kolumn i milionów wierszy.

Skoro większość użytkowników obejrzało zaledwie niewielką liczbę filmów, dominującą wartością elemnetów macierzy będzie zero.

Macierz rzadka to macierz, w której większość elementów stanowią zera. Przechowuje ona jedynie elementy niezerowe. Zakłada się, że pozostałymi elementami są zera.

Zaprezentowane podejście pozwala na znaczne zmniejszenie obciążenia związanego z przetwarzaniem takiej macierzy.

W zaprezentowanym przykładzie, utworzyłąm tablicę NumPy z dwoma wartościami niezerowymi, a następnie skonwertowałam ją do postaci macierzy rzadkiej.

Po wyświetleniu macierzy rzadkiej można zobaczyć, że przechowuje ona jedynie wartości niezerowe.

Istnieje pewna liczba typów macierzy rzadkiej.

W przypadku typu CSR (ang. compressed sparse row) - przedstawiają indeksy wartości niezerowych.

Na przykład element 1  znajduje się drugim wierszu i drugiej kolumnie.

Zalety istnienia macierzy rzadkiej ujawniają się w przypadku istnienia znacznie większej macierzy wraz z wieloma zerami.

In [ ]:
#Utworzenie większej macierzy
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0],
                          [0, 1, 0, 0, 0, 0, 0],
                          [3, 0, 0, 0, 0, 0, 0]])

#Utworzenie macierzy w formacie CSR

matrix_large_sparse = sparse.csr_matrix(matrix_large)

In [ ]:
matrix_large

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [3, 0, 0, 0, 0, 0, 0]])

In [ ]:
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3


Jak możesz zauważyć, pomimo dodania wielu elemntów zerowych w macierzy matrix_large, utworzona na jej podstawie macierz rzadka jest dokładnie taka sama jak zdefinowana na początku.

Dodanie elemntów zerowych nie spowodowało zmiany wielkości macierzy rzadkiej.

Podsumowując ten rozdział należy wskazać, iż istnieje wiele typów macierzy rzadkiej m.in. CSC (ang. compossed sparse column), lista list czy też słownik kluczy.
Podkreśla się, że nie ma "najlepszego" typu macierzy rzadkiej.

Istnieją między nimi znaczne różnice, które należy uwzględnić podczas wyboru konkretnego typu.

###Zadanie 3. Dokonaj wstępnej alokacji tablicy o podanej wielkości zawierajacej pewne wartości.

Biblioteka NumPy posiada funkcje przeznaczone do generowania wektorów i macierzy dowolnej wielkości przy użyciu na przykład wartości 0, 1 lub innej dowolnie wybranej.

In [ ]:
#Wczytywanie biblioteki
import numpy as np
#Utworzenie wektora o kształcie (1, 5), składającego się wyłącznie z zer
vector = np.zeros(shape=5)
print(vector)


#Wygenerowanie macierzy o kształcie (3, 3) składajacej się wyłącznie z jedynek
matrix = np.full(shape=(3,3), fill_value=1)
print(matrix)


[0. 0. 0. 0. 0.]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


Wygenerowanie tablicy wypełnionej pewnymi danymi okazuje się użyteczne z wielu powodów, między innymi takich jak zapewnienie większej wydajności działania kodu badź używanie danych syntetycznych do przetestowania algorytmów.

W wielu językach programowaniawstępna alokacja tablicy z wykorzystaniem wartości domyślej (najcześciej jest to 0) jest uznawana za powszechnie stosowaną praktykę.

###Zadanie 4. Pobieranie elemntów

Należy pobrać co najmniej jeden elemnet z wektora lub macierzy.

In [ ]:
#Wczytanie biblioteki
import numpy as np
#Utworzenie wiersza wektora
vector = np.array([1, 2, 3, 4, 5, 6])
#Utworzenie macierzy
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [ ]:
#Pobranie trzeciego elemntu wektora (elemntu o indeksie 2)
vector[2]

3

In [ ]:
#Pobranie elemntu znajdującego się w drugim wierszu i drugiej kolumnie macierzy matrix

matrix[1,1]

5

Podobnie jak wprzypadku wielu innych struktr Pythona, również tablice NumPy posiadają indeksy liczone od 0.

Posiadając tę wiedzę mamy możliwość korzystania z wielu metod przeznaczonych do pobierania (np. za pomocą indeksu lub wycinka) elemntów lub grup elemnetów w tablicy.

Pobranie wszytskich elemnetów wektora

In [ ]:
vector[:]


array([1, 2, 3, 4, 5, 6])

Pobranie wszytskich elementów wektora do trzeciego włącznie

In [ ]:
vector[:3]

array([1, 2, 3])

Podbranie wszytskich elementów od czwartego włącznie

In [ ]:
vector[3:]

array([4, 5, 6])

Pobranie ostatniego elemnetu

In [ ]:
vector[-1]

6

Odwórcenie wektora

In [ ]:
vector[::-1]

array([6, 5, 4, 3, 2, 1])

Pobranie elemntu macierzy znajdującego się w trzecim wierszu i trzeciej kolumnie

In [ ]:
matrix[2, 2]

9

Pobranie pierwszych dwóch wierszy i wszytskich kolumn

In [ ]:
matrix[:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

Pobranie wszystkich wierszy i drugiej kolumny

In [ ]:
matrix[:, 1:2]

array([[2],
       [5],
       [8]])

###Zadanie 5. Opisywanie macierzy

Opiszmy kształt, wielkość i wymiar macierzy - w tym celu skorzystamy z oferowanych przez bibliotekę Numpy krotek shape, size oraz ndim

In [ ]:
#Wczytanie biblioteki
import numpy as np
#Utworzenie macierzy
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 13]])

#Wyświetl liczbę wierszy i kolumn
print(matrix.shape)
#Wyświetlenie liczby elemnetów (wiersze x kolumny)
print(matrix.size)
#Wyświetlenie liczby wymiarów
print(matrix.ndim)

(3, 4)
12
2


###Zadanie 6. Przeprowadzenie operacji na wszytskich elemnetach

Aby przeprowadzić operację na wszystkich elemnetach tablicy użyj oferowanej prze bibliotekę NumPy metodę vectorize().

In [ ]:
#Wczytanie biblioteki
import numpy as np
#Utworzenie macierzy
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
#Utworzenie funkcji dodającej 100 do istniejącej wartości
add_100 = lambda x: x + 100

#Utworzenie funkcji bazującej na metodzie vectorize()
vectorized_add_100 = np.vectorize(add_100)

#Wywołanie funkcji dla wszytskich elementów macierzy
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

Zdefiniowana w bibliotece NumPy metoda vectorize() przeprowadza konwersję funkcji na postać, którą można wywołać dla wszytskich elemnetów tablicy bądź też wycinka tablicy.

Warto w tym miejscu wspomnieć, iż działanie tej metody przypomina pętlę for przeprowadzajacą iterację przez elemnety.

Co więcej tablica NumPy pozwala na wykonywanie operacji między tablicami, nawet jeśli ich wymiary są inne - **broadcasting**.



Bazując na metodzie broadcastingu, można przygotować znacznie prostszą wersję omawianego tutaj rozwiązania.

In [ ]:
#Wczytanie biblioteki
import numpy as np
#Utworzenie macierzy
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

matrix += 100
print(matrix)

[[101 102 103]
 [104 105 106]
 [107 108 109]]


Wprowadzenie broadcastingu nie działa dla wszystkich kształtów oraz w każdej sytuacji, ale stanowi powszechnie używany sposób na przeprowadzenie pewnych operacji dla wszytskich elementów tablicy biblioteki NumPy.

###Zadanie 7. Znajdowanie wartości maksymalnej i minimalnej

Aby znależć wartosć maksymalną i minimalną w tablicy nalezy użyć oferowanych przez bibliotekę numpy metod max() oraz min().

Użycie parametru axis pozwala na przeprowadzenie operacji względem podanej osi.

In [ ]:
#Wczytywanie biblioteki
import numpy as np
#Utworzenie macierzy
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
#Zwrot elementu o maksymalnej wartości
print(np.max(matrix))

#Zwrot elementu o minimalnej wartości
print(np.min(matrix))

9
1


In [ ]:
#Wyszukanie w każdej kolumnie elemnetu o maksymalnej wartości

print(matrix)
print(10 * '*')
print(np.max(matrix, axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
**********
[7 8 9]


In [ ]:
matrix = np.array([[1, 10, 12],
                   [3, 12, 98],
                   [3, 89, 100]])

print(np.max(matrix, axis=0))

[  3  89 100]


In [ ]:
#Wyszukanie w każdem wierszu elemnetu o maksymalnej wartości

print(matrix)
print(10 * '*')
print(np.max(matrix, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
**********
[3 6 9]


In [ ]:
matrix = np.array([[1, 10, 12],
                   [3, 12, 98],
                   [3, 89, 100]])

print(np.max(matrix, axis=1))

[ 12  98 100]


###Zadanie 8. Obliczanie średniej, wariancji i odchylenia standardowego

Aby uzyskać wybrane dane statystyczne dotyczace tablicy należy skorzystać z oferowanych przez bibliotekę numpy metod mean() - średnia, var() - wariancja, std() - odchylenie standardowe.

In [ ]:
#Wczytanie biblioteki
import numpy as np
#Utworzenie macierzy
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
#Zwrot wartości średniej
print(np.mean(matrix))
#Zwrot wariancji
print(np.var(matrix))
#Zwrot odchylenia standardowego
print(np.std(matrix))

5.0
6.666666666666667
2.581988897471611


Podobnie jak w przypadku metod max() i min() można w prosty sposób otrzymać wybrane dane statystyczne  dotyczace całej macierzy lub tylko jednej osi.

In [ ]:
#Wyszukanie wartości średniej w każdej kolumnie
np.mean(matrix, axis=0)

array([4., 5., 6.])

###Zadanie 9. Zmiana kształtu tablicy

Aby zmienić kształt (liczbę wierszy i kolumn) tablicy bez modyfikowania wartości jej elemnetów należy użyć oferowanej przez bibliotekę NumPy metody reshape().

In [ ]:
#Wczytanie biblioteki
import numpy as np

#Utworzeznie macierzy o wielkości 4x3
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

#Zmiana kształtu macierzy na (2, 6)
matrix = matrix.reshape(2, 6)
print(matrix)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


Metoda reshape() pozwala na przeprowadzenie restrukturyzacji tablicy w taki sposób, aby zachowała te same dane, ale przechowywane za pomocą innej liczby wierszy i kolumn.

Jedynym wymogiem jest zachowanie tej samej liczby elementów przez macierze poczatkowa i zmodyfikowaną.

Innymi słowy - muszą mieć one tę samą wielkość.

Jak zostało to zaprezentowane nieco wcześniej, do sprawdzenia wielkości macierzy można użyć metody size().


Jednym z bardzo użytecznych argumentów metody reshape() jest -1, który oznacza dowolną wymaganą liczbę.

Dlatego też wywoałanie reshape(1, -1) oznacza jeden wiersz i dowolną wymaganą liczbę kolumn

In [ ]:
matrix.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

W przypadku podania tylko jednej liczby całkowitej wartością zwrotną metody reshape() będzie tablica jednowymiarowa o podanej wielkości.

In [ ]:
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

###10. Transponowanie wektora lub macierzy

Jeżeli potrzebujesz przeprowadzić transponowanie wektora lub macierzy użyj oferowanego przez bibliotekę NumPy atrybutu T.

In [ ]:
#Wczytanie biblioteki
import numpy as np
#Utworzenie macierzy
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
#Transponowanien macierzy
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

**Transponowanie** - dość często przeprowadzana w algebrze liniowej operacja, w trakcie której następuje zamiana miejscami indeksów kolumn i wierszy każdego elemntu.

Należy wskazać, iż formalnie wektor nie może być transponowany, ponieważ jest po prostu kolekcją wartości.

In [ ]:
vector = np.array([1, 2, 3, 4])
vector

array([1, 2, 3, 4])

In [ ]:
vector.T

array([1, 2, 3, 4])

Mimo to powszechnie używa się pojęcia 'transponowanie' w odniesieniu do konwersji wiersza wektora na kolumnę bądź na odwót.

Uwaga! Zwróć uwagę na drugi nawias kwadratowy

In [ ]:
vector = np.array([[1, 2, 3, 4]])
vector

array([[1, 2, 3, 4]])

In [ ]:
vector.T

array([[1],
       [2],
       [3],
       [4]])

###Zadanie 11. Spłaszczanie macierzy

Jeżeli potrzebujesz przekształcić macierz w tablicę jednowymiarową, użyj oferowanej przez bibliotekę NumPy metody flatten()

In [ ]:
#Wczytanie biblioteki
import numpy as np
#Utworzenie macierzy
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
#Spłaszczanie macierzy
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

flatten() to metoda pozwalająca na przekształcenie macierzy w tablicę jednowymiarową.

Alternatywne rozwiązanie polega na użyciu metody reshape() do utworzenia wiersza wektora.

In [ ]:
matrix.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

Inny sposób spłaszczenia tablicy polega na użyciu metody ravel().

W przeciwieństwie do metody flatten() zwracającej kopię pierwotnej tablicy, metoda ravel() działa na wskazanym obiekcie i dlatego jest nieco szybsza.

Ponadto umożliwia spłaszczenie listy tablic, co okazuje się niemożliwe w przypadku metody flatten().

Metoda ta będzie użyteczna w przypadku spłaszczania naprawdę ogromnych tablic i przyspieszy wykonywanie kodu.

In [ ]:
#Utworzenie pierwszej macierzy
matrix_1 = np.array([[1, 2],
                     [3, 4]])

#Utworzenie drugiej macierzy
matrix_2 = np.array([[5, 6],
                     [7, 8]])

#Utworzenie listy macierzy
matrix_list = [matrix_1, matrix_2]

#Spłaszczanie całej listy macierzy
np.ravel(matrix_list)

array([1, 2, 3, 4, 5, 6, 7, 8])

###Zadanie 12. Znajdowanie rzędu macierzy

Jeżeli chcesz znaleźć rząd macierzy skorzystaj z oferowanej przez bibliotekę NumPy metody matrix_rank() z zakresu algebry liniowej.

In [ ]:
#Wczytywanie biblioteki
import numpy as np
#Utworzenie macierzy
matrix = np.array([[1, 1, 1],
                   [1, 1, 10],
                   [1, 1, 15]])

#Zwraca rząd macierzy
np.linalg.matrix_rank(matrix)

2

**Rząd macierzy** to wymiar przestrzeni wektora obejmowanej przez jego kolumny lub wiersze.

###Zadanie 13. Pobieranie przekątnej macierzy

Jeżeli chcesz pobrać elemnety leżące na przekątnej macierzy uzyj oferowanej przez bibliotekę NumPy metody *diagonal()*.

In [ ]:
#Wczytywanie biblioteki
import numpy as np
#Utworzenie macierzy
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

#Zwrot elemnetów znajdujących się na przekątnej macierzy
matrix.diagonal()

array([1, 4, 9])

Poza metodą diagonal() istnieje również inna możliwość pobrania elementów znajdujących się na przekątnej innej niż głowna - wymaga to użycia parametru offsets.

In [ ]:
matrix.diagonal(offset=1)

array([2, 6])

In [ ]:
matrix.diagonal(offset=-2)

array([3])

###Zadanie 14. Obliczanie śladu macierzy

Jeśli chcesz obliczyć ślad macierzy skorzystaj z oferowanej przez bibliotekę NumPy metody trace()

In [ ]:
#Wczytywanie biblioteki
import numpy as np
#Utworzenie macierzy
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])
matrix.trace()

14

**Ślad macierzy** - suma elementów przekątnej- ta wartość bardzo często jest wykorzystywana w tle przez metody uczenia maszynowego.

Mając tablicę wielowymiarową NumPy można obliczyć jej ślad za pomoca metody trace().

Istnieje również możliwość zwrotu przekątnej macierzy i jednoczesnego obliczenia sumy elementów leżących na przekątnej. Przykład zaprezentowano w dalszym fragmencie kodu.

In [ ]:
#Zwrot sumy elementów leżących na przekątnej macierzy
sum(matrix.diagonal())

14

###Zadanie 15. Obliczanie iloczynu skalarnego

Jeżeli potrezebujesz obliczyć iloczyn skalarny dwóch wektorów użyj oferowanej przez bibliotekę NumPy metody *dot()*.

In [ ]:
#Wczytywanie biblioteki
import numpy as np
#Utworzenie dwóch wektorów
vector_1 = np.array([1, 2, 3])
vector_2 = np.array([4, 5, 6])
#Obliczanie iloczynu skalarnego
np.dot(vector_1, vector_2)

32

Iloczyn skalarny dwóch wektorów a i b, można zdefiniować za pomocą następującego wzoru:

w którym

Alternatywne rozwiązanie w Pythonie 3.5 i nowszych wersjach polega na użyciu nowego operatora @, jak pokazano w poniższym fragmencie kodu.

In [ ]:
vector_1 @ vector_2

32

###Zadanie 16. Dodawanie i odejmowanie macierzy

Jeżeli chcesz przeprowadzić operacje dodawania lub odejmowania macierzy użyj oferowanych przez bibliotekę NumPy metod *add()* oraz *subtract(*).

In [ ]:
#Wczytanie biblioteki
import numpy as np

#Utworzenie macierzy
matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])

matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 3]])

#Dodawanie dwóch macierzy
print(np.add(matrix_a, matrix_b))

#Odejmowanie dwóch macierzy
print(np.subtract(matrix_a, matrix_b))

[[2 4 2]
 [2 4 2]
 [2 4 5]]
[[ 0 -2  0]
 [ 0 -2  0]
 [ 0 -2 -1]]


Alternatywne rozwiązanie w zakresie dodawania i odejmowania macierzy polega na użyciu operatorów - odpoiwiednio + i -

In [ ]:
#Dodawanie dwóch macierzy
matrix_a + matrix_b

array([[2, 4, 2],
       [2, 4, 2],
       [2, 4, 5]])

###Zadanie 17. Mnożenie macierzy

Jeżeli chcesz pomnożyć dwie macierze skorzystaj z oferowanej przez bibliotekę NumPy metody *dot()*.

In [ ]:
#Wczytywanie biblioteki
import numpy as np
#Utworzenie macierzy
matrix_a = np.array([[1, 1],
                    [1, 2]])
matrix_b = np.array([[1, 3],
                     [1, 2]])

#Mnożenie dwóch macierzy
np.dot(matrix_a, matrix_b)

array([[2, 5],
       [3, 7]])

Rozwiązaniem alternatywnym w Pythonie 3.5 i nowszych wersjach jest użycie operatora @.

In [ ]:
#Mnożenie dwóch macierzy
matrix_a @ matrix_b

array([[2, 5],
       [3, 7]])

Jeżeli chcesz przeprowadzić operację uwzględniającą również elementy, powinieneś użyć operatora *

In [ ]:
#Mnożenie dwóch macierzy z uwzględnieniem ich elemnetów
matrix_a * matrix_b

array([[1, 3],
       [1, 4]])

###Zadanie 18. Odwracanie macierzy

Jeżeli chcesz otrzymać macierz odwrotną dla danej macierzy kwadratowej użyj oferowanej przez bibliotekę NumPy metody inv() z zakresu algebry liniowej.

In [ ]:
#Wczytanie biblioteki
import numpy as np

#Utworzenie macierzy
matrix = np.array([[1, 4],
                   [2, 5]])

#Utworzenie macierzy odwrotnej
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

Odwrotnością macierzy kwadratowej $A$ jest druga macierz $ A^{-1} $, na przykłąd:

 $ A *A^{-1} $ = $I$

 gdzie I to macierz tożsamościowa.
 Do utworzenia macierzy odwrotnej można użyć zdefiniowanej w bibliotece NumPy metody linalg.inv().

 Aby zademonstrować jej działanie, w omawianym przykładzie macierz zostanie pomnożona przez jej odwrotność, a wynikiem jest macierz tożsamościowa.





In [ ]:
#Mnożenie macierzy i jej odwrotności
matrix @ np.linalg.inv(matrix)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

###Zadanie 19. Generowanie liczb losowych

Jeżeli chcesz wygenerować liczby pseudolosowe użyj oferowanej przez bibliotekę NumPy klasy random.

In [ ]:
#Wczytanie biblioteki
import numpy as np
#Zdefiniowanie wartości zalążka
np.random.seed(0)
#Wygenerowanie trzech losowych liczb zmiennoprzecinkowych z przedziału od 0.0 do 1.0
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

Byblioteka Numpy oferuje wiele możliwości w zakresie generowania liczb pseudolosowych. W przedstawionym powyżej rozwiązaniu zostały wygenerowane liczby zmiennoprzecinkowe. Zastosowane tu podejście jest również często stosowane podczas generowania liczb całkowitych.

In [ ]:
#Wygenerowanie trzech pseudolosowych liczb całkowitych z przedziału od 1 do 10.
np.random.randint(0, 11, 3)

array([3, 7, 9])

Alternatywne podejście polega na wygenerowaniu liczb poprzez pobranie ich z rozkładu (formalnie rzecz ujmując nie będą to liczby losowe).

In [ ]:
#Pobieranie trzech liczb z rozkładu zwykłego o średniej wynoszącej 0.0 i odchyleniu standardowym wynoszącym 1.0.
np.random.normal(0.0, 1.0, 3)

array([-1.42232584,  1.52006949, -0.29139398])

In [ ]:
#Pobranie trzech liczb z rozkładu logistycznego o średniej wynoszącej 0.0 i skali równej 1.0
np.random.logistic(0.0, 1.0, 3)

array([-0.98118713, -0.08939902,  1.46416405])

In [ ]:
#pobranie trzech liczb większych niż lub równych 1.0 i mniejszych niż 2.0
np.random.uniform(1.0, 2.0, 3)

array([1.47997717, 1.3927848 , 1.83607876])

Czasami użyteczne jest wielokrotne zwracanie tych samych liczb losowych, aby zapewnić przewidywalne i powtarzalne rozwiązania. W takim przypadku można wykorzystać tak zwaną "wartość zalążka" (liczbę całkowitą) generatora liczb pseudolosowych.

Uruchomienie generatora z tą samą wartością zalążka zawsze spowoduje wygenerowanie tych samych danych wyjściowych.